_G.pg.item_data_statistics[16013] = {
	display = "방어 스킬 강화용 교본 T3, \n전술학원에서 함선 소녀의 스킬을 강화하는 데에 사용된다.",
	name = "방어 교본 T3",
	rarity = 4,
	type = 10,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 16013,
	is_world = 0,
	icon = "Props/16013",
	display_icon = {},
	price = {},
	index = {}
}
