_G.pg.item_data_statistics[59137] = {
	display = "『디바인 트래지코미디』 이벤트에서 교환, 이벤트 종료 후 소실됨. ",
	name = "제국의 영광 ",
	rarity = 2,
	type = 98,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59137,
	is_world = 0,
	icon = "Props/yidali_pt",
	display_icon = {},
	price = {},
	index = {}
}
