_G.pg.item_data_statistics[60148] = {
	display = "만화 퍼즐 조각9",
	name = "만화 퍼즐 조각9",
	rarity = 2,
	type = 0,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 1,
	link_id = 20747,
	id = 60148,
	is_world = 0,
	icon = "Props/javelin",
	display_icon = {},
	price = {},
	index = {}
}
