_G.pg.item_data_statistics[10003] = {
	display = "방뢰 벌지 T3 설계도",
	name = "방뢰 벌지 T3 설계도",
	rarity = 3,
	type = 9,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 10003,
	is_world = 0,
	icon = "Equips/1300",
	display_icon = {},
	price = {},
	index = {}
}
