_G.pg.item_data_statistics[55001] = {
	display = "일정 확률로 다음의 설계도를 얻을 수 있습니다.",
	name = "랜덤 설계도",
	rarity = 1,
	type = 99,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 55001,
	is_world = 0,
	icon = "Props/55000",
	display_icon = {},
	price = {},
	index = {}
}
