_G.pg.item_data_statistics[10118] = {
	display = "37mm 대공포 70-K T3 설계도",
	name = "37mm 대공포 70-K T3 설계도",
	rarity = 3,
	type = 9,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 10118,
	is_world = 0,
	icon = "Equips/85180",
	display_icon = {},
	price = {},
	index = {}
}
