slot0 = class("NewEducateConst")
slot0.NEW_EDUCATE_SELECT_ID = "NEW_EDUCATE_SELECT_ID"
slot0.NEW_EDUCATE_SKIP_PLANS_ANIM = "NEW_EDUCATE_SKIP_PLANS_ANIM"
slot0.NEW_EDUCATE_EVENT_TIP = "NEW_EDUCATE_EVENT_TIP"
slot0.NEW_EDUCATE_NEW_CHILD_TIP = "NEW_EDUCATE_NEW_CHILD_TIP"
slot0.DROP_TYPE = {
	ATTR = 1,
	RES = 2,
	POLAROID = 3,
	BUFF = 4
}
slot0.CONDITION_TYPE = {
	ATTR_SUM = 2,
	DROP = 1,
	NORMAL_SITE_CNT = 5,
	ROUND = 4,
	EVENT_SITE_CNT = 3
}
slot0.PERFORM_TYPE = {
	MINIGAME = 3,
	WORD = 4,
	STORY = 5,
	PICTURE = 7,
	OPTION = 2,
	BUBBLE = 6,
	CPK = 1
}
slot0.WORD_TYPE = {
	HIDE_IMAGE = 6,
	PLAYER = 2,
	SITE_RIGHT = 5,
	CHILD = 1,
	SITE_ASIDE = 0,
	ASIDE = 3,
	SITE_LEFT = 4
}
slot0.SITE_TYPE = {
	SHOP = 2,
	EVENT = 5,
	WORK = 3,
	SHIP = 1,
	TRAVEL = 4
}
slot0.SITE_NORMAL_TYPE = {
	TRAVEL = 2,
	WORK = 1
}
slot0.SITE_STATE_TYPE = {
	SHIP = 3,
	NORMAL = 2,
	EVENT = 1
}
slot0.EFFECT_TYPE = {
	REDUCE_GOODS_CSOT = 23,
	EXTRA_PLAN = 7,
	REDUCE_PLAN_COST = 22
}
slot0.TYPEWRITE_SPEED = 0.05
slot0.TYPEWRITE_SPEED_UP = 0.01
slot0.LOCK_ENDING = false
slot0.LOCK_GUIDE = false

return slot0
