pg = pg or {}
pg.medal_template = {
	[10011] = {
		target_id = "0",
		name = "Naval Service Medal",
		target_num = 2000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made great contributions and emerged victorious through many battles.",
		next = 10012,
		icon = "2021",
		page = 1,
		target_type = 1022,
		start = 0,
		hide = 0,
		label = "l_201",
		condition = "Obtain 2,000 victories.",
		rank = 1,
		id = 10011,
		explain1 = "for numerous victories in battle.",
		explain2 = "Awarded to courageous naval personnel"
	},
	[10012] = {
		target_id = "0",
		name = "Naval Service Medal",
		target_num = 4000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made great contributions and emerged victorious through many battles.",
		next = 10013,
		icon = "2022",
		page = 1,
		target_type = 1022,
		start = 1,
		hide = 0,
		label = "l_201",
		condition = "Obtain 4,000 victories.",
		rank = 2,
		id = 10012,
		explain1 = "for numerous victories in battle.",
		explain2 = "Awarded to courageous naval personnel"
	},
	[10013] = {
		target_id = "0",
		name = "Naval Service Medal",
		target_num = 10000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made great contributions and emerged victorious through many battles.",
		next = 10014,
		icon = "2023",
		page = 1,
		target_type = 1022,
		start = 1,
		hide = 0,
		label = "l_201",
		condition = "Obtain 10,000 victories.",
		rank = 3,
		id = 10013,
		explain1 = "for numerous victories in battle.",
		explain2 = "Awarded to courageous naval personnel"
	},
	[10014] = {
		target_id = "0",
		name = "Naval Service Medal",
		target_num = 20000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made great contributions and emerged victorious through many battles.",
		next = 10015,
		icon = "2024",
		page = 1,
		target_type = 1022,
		start = 1,
		hide = 0,
		label = "l_201",
		condition = "Obtain 20,000 victories.",
		rank = 4,
		id = 10014,
		explain1 = "for numerous victories in battle.",
		explain2 = "Awarded to courageous naval personnel"
	},
	[10015] = {
		target_id = "0",
		name = "Naval Service Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made great contributions and emerged victorious through many battles.",
		next = 0,
		icon = "2025",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_201",
		condition = "Coming Soon",
		rank = 5,
		id = 10015,
		explain1 = "for numerous victories in battle.",
		explain2 = "Awarded to courageous naval personnel"
	},
	[10021] = {
		target_id = "0",
		name = "Naval Devotion Medal",
		target_num = 100,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10022,
		desc = "To the commander who carried out their duty and completed missions with their ships.",
		next = 10022,
		icon = "2051",
		page = 1,
		target_type = 91,
		start = 0,
		hide = 0,
		label = "l_202",
		condition = "Complete 100 Daily Missions.",
		rank = 1,
		id = 10021,
		explain1 = "Awarded to diligent naval personnel",
		explain2 = "for earnestly completing missions."
	},
	[10022] = {
		target_id = "0",
		name = "Naval Devotion Medal",
		target_num = 300,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10023,
		desc = "To the commander who carried out their duty and completed missions with their ships.",
		next = 10023,
		icon = "2052",
		page = 1,
		target_type = 91,
		start = 1,
		hide = 0,
		label = "l_202",
		condition = "Complete 300 Daily Missions.",
		rank = 2,
		id = 10022,
		explain1 = "Awarded to diligent naval personnel",
		explain2 = "for earnestly completing missions."
	},
	[10023] = {
		target_id = "0",
		name = "Naval Devotion Medal",
		target_num = 800,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10024,
		desc = "To the commander who carried out their duty and completed missions with their ships.",
		next = 10024,
		icon = "2053",
		page = 1,
		target_type = 91,
		start = 1,
		hide = 0,
		label = "l_202",
		condition = "Complete 800 Daily Missions.",
		rank = 3,
		id = 10023,
		explain1 = "Awarded to diligent naval personnel",
		explain2 = "for earnestly completing missions."
	},
	[10024] = {
		target_id = "0",
		name = "Naval Devotion Medal",
		target_num = 1600,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10025,
		desc = "To the commander who carried out their duty and completed missions with their ships.",
		next = 10025,
		icon = "2054",
		page = 1,
		target_type = 91,
		start = 1,
		hide = 0,
		label = "l_202",
		condition = "Complete 1,600 Daily Missions.",
		rank = 4,
		id = 10024,
		explain1 = "Awarded to diligent naval personnel",
		explain2 = "for earnestly completing missions."
	},
	[10025] = {
		target_id = "0",
		name = "Naval Devotion Medal",
		target_num = 3200,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who carried out their duty and completed missions with their ships.",
		next = 0,
		icon = "2055",
		page = 1,
		target_type = 91,
		start = 1,
		hide = 0,
		label = "l_202",
		condition = "Complete 3,200 Daily Missions.",
		rank = 5,
		id = 10025,
		explain1 = "Awarded to diligent naval personnel",
		explain2 = "for earnestly completing missions."
	},
	[10031] = {
		target_id = "5",
		name = "Seaborne Explorer Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10032,
		desc = "To the commander who explored the sea and sought out chance encounters with fate.",
		next = 10032,
		icon = "2031",
		page = 1,
		target_type = 141,
		start = 0,
		hide = 0,
		label = "l_203",
		condition = "Acquire 1 SR ship from a Story or Event Map.",
		rank = 1,
		id = 10031,
		explain1 = "for always facing the sea's challenges.",
		explain2 = "Awarded to adventurous naval personnel"
	},
	[10032] = {
		target_id = "5",
		name = "Seaborne Explorer Medal",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10033,
		desc = "To the commander who explored the sea and sought out chance encounters with fate.",
		next = 10033,
		icon = "2032",
		page = 1,
		target_type = 141,
		start = 1,
		hide = 0,
		label = "l_203",
		condition = "Acquire 3 SR ships from Story or Event Maps.",
		rank = 2,
		id = 10032,
		explain1 = "for always facing the sea's challenges.",
		explain2 = "Awarded to adventurous naval personnel"
	},
	[10033] = {
		target_id = "5",
		name = "Seaborne Explorer Medal",
		target_num = 10,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 10034,
		desc = "To the commander who explored the sea and sought out chance encounters with fate.",
		next = 10034,
		icon = "2033",
		page = 1,
		target_type = 141,
		start = 1,
		hide = 0,
		label = "l_203",
		condition = "Acquire 10 SR ships from Story or Event Maps.",
		rank = 3,
		id = 10033,
		explain1 = "for always facing the sea's challenges.",
		explain2 = "Awarded to adventurous naval personnel"
	},
	[10034] = {
		target_id = "5",
		name = "Seaborne Explorer Medal",
		target_num = 20,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who explored the sea and sought out chance encounters with fate.",
		next = 10035,
		icon = "2034",
		page = 1,
		target_type = 141,
		start = 1,
		hide = 0,
		label = "l_203",
		condition = "Acquire 20 SR ships from Story or Event Maps.",
		rank = 4,
		id = 10034,
		explain1 = "for always facing the sea's challenges.",
		explain2 = "Awarded to adventurous naval personnel"
	},
	[10035] = {
		target_id = "0",
		name = "Seaborne Explorer Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who explored the sea and sought out chance encounters with fate.",
		next = 0,
		icon = "2035",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_203",
		condition = "Coming Soon",
		rank = 5,
		id = 10035,
		explain1 = "for always facing the sea's challenges.",
		explain2 = "Awarded to adventurous naval personnel"
	},
	[10041] = {
		target_id = "0",
		name = "Renovation Merit Medal",
		target_num = 3000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made their Port and Dorm a lovelier place for their ships to return to.",
		next = 10042,
		icon = "2041",
		page = 1,
		target_type = 133,
		start = 0,
		hide = 0,
		label = "l_204",
		condition = "Spend a total of 3,000 Decor Tokens.",
		rank = 1,
		id = 10041,
		explain1 = "for improving living conditions.",
		explain2 = "Awarded to considerate naval personnel"
	},
	[10042] = {
		target_id = "0",
		name = "Renovation Merit Medal",
		target_num = 7000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made their Port and Dorm a lovelier place for their ships to return to.",
		next = 10043,
		icon = "2042",
		page = 1,
		target_type = 133,
		start = 1,
		hide = 0,
		label = "l_204",
		condition = "Spend a total of 7,000 Decor Tokens.",
		rank = 2,
		id = 10042,
		explain1 = "for improving living conditions.",
		explain2 = "Awarded to considerate naval personnel"
	},
	[10043] = {
		target_id = "0",
		name = "Renovation Merit Medal",
		target_num = 15000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made their Port and Dorm a lovelier place for their ships to return to.",
		next = 10044,
		icon = "2043",
		page = 1,
		target_type = 133,
		start = 1,
		hide = 0,
		label = "l_204",
		condition = "Spend a total of 15,000 Decor Tokens.",
		rank = 3,
		id = 10043,
		explain1 = "for improving living conditions.",
		explain2 = "Awarded to considerate naval personnel"
	},
	[10044] = {
		target_id = "0",
		name = "Renovation Merit Medal",
		target_num = 30000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made their Port and Dorm a lovelier place for their ships to return to.",
		next = 10045,
		icon = "2044",
		page = 1,
		target_type = 133,
		start = 1,
		hide = 0,
		label = "l_204",
		condition = "Spend a total of 30,000 Decor Tokens.",
		rank = 4,
		id = 10044,
		explain1 = "for improving living conditions.",
		explain2 = "Awarded to considerate naval personnel"
	},
	[10045] = {
		target_id = "0",
		name = "Renovation Merit Medal",
		target_num = 60000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who made their Port and Dorm a lovelier place for their ships to return to.",
		next = 0,
		icon = "2045",
		page = 1,
		target_type = 133,
		start = 1,
		hide = 0,
		label = "l_204",
		condition = "Spend a total of 60,000 Decor Tokens.",
		rank = 5,
		id = 10045,
		explain1 = "for improving living conditions.",
		explain2 = "Awarded to considerate naval personnel"
	},
	[10051] = {
		target_id = "10000",
		name = "Rose Vows Award",
		target_num = 10,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the person who cares about those serving them not just as ships, but as people.",
		next = 10052,
		icon = "2061",
		page = 1,
		target_type = 1019,
		start = 0,
		hide = 0,
		label = "l_205",
		condition = "Achieve 100+ Affinity with 10 ships.",
		rank = 1,
		id = 10051,
		explain1 = "with ships as well as people.",
		explain2 = "Awarded to those who form bonds"
	},
	[10052] = {
		target_id = "10000",
		name = "Rose Vows Award",
		target_num = 20,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the person who cares about those serving them not just as ships, but as people.",
		next = 10053,
		icon = "2062",
		page = 1,
		target_type = 1019,
		start = 1,
		hide = 0,
		label = "l_205",
		condition = "Achieve 100+ Affinity with 20 ships.",
		rank = 2,
		id = 10052,
		explain1 = "with ships as well as people.",
		explain2 = "Awarded to those who form bonds"
	},
	[10053] = {
		target_id = "10000",
		name = "Rose Vows Award",
		target_num = 50,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the person who cares about those serving them not just as ships, but as people.",
		next = 10054,
		icon = "2063",
		page = 1,
		target_type = 1019,
		start = 1,
		hide = 0,
		label = "l_205",
		condition = "Achieve 100+ Affinity with 50 ships.",
		rank = 3,
		id = 10053,
		explain1 = "with ships as well as people.",
		explain2 = "Awarded to those who form bonds"
	},
	[10054] = {
		target_id = "10000",
		name = "Rose Vows Award",
		target_num = 100,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the person who cares about those serving them not just as ships, but as people.",
		next = 10055,
		icon = "2064",
		page = 1,
		target_type = 1019,
		start = 1,
		hide = 0,
		label = "l_205",
		condition = "Achieve 100+ Affinity with 100 ships.",
		rank = 4,
		id = 10054,
		explain1 = "with ships as well as people.",
		explain2 = "Awarded to those who form bonds"
	},
	[10055] = {
		target_id = "10000",
		name = "Rose Vows Award",
		target_num = 200,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the person who cares about those serving them not just as ships, but as people.",
		next = 0,
		icon = "2065",
		page = 1,
		target_type = 1019,
		start = 1,
		hide = 0,
		label = "l_205",
		condition = "Achieve 100+ Affinity with 200 ships.",
		rank = 5,
		id = 10055,
		explain1 = "with ships as well as people.",
		explain2 = "Awarded to those who form bonds"
	},
	[10061] = {
		name = "Eagle Union Emblem of Liberty",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who embodies the ideals of the Eagle Union as a protector of liberty and justice.",
		next = 10062,
		icon = "1011",
		page = 1,
		target_type = 160,
		start = 0,
		hide = 0,
		label = "l_101",
		condition = "Using Eagle Union ships: Reach Level 120 on at least 12 different ships, reach a total of at least 2,000 Affinity, and earn at least 2M EXP.",
		rank = 1,
		id = 10061,
		explain1 = "Awarded to those who bless the seas",
		explain2 = "with liberty and justice.",
		target_id = {
			100611,
			100621,
			100631
		}
	},
	[10062] = {
		name = "Eagle Union Emblem of Liberty",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who embodies the ideals of the Eagle Union as a protector of liberty and justice.",
		next = 10063,
		icon = "1012",
		page = 1,
		target_type = 160,
		start = 1,
		hide = 0,
		label = "l_101",
		condition = "Using Eagle Union ships: Reach Level 120 on at least 24 different ships, reach a total of at least 4,000 Affinity, and earn at least 2M EXP.",
		rank = 2,
		id = 10062,
		explain1 = "Awarded to those who bless the seas",
		explain2 = "with liberty and justice.",
		target_id = {
			100612,
			100622,
			100632
		}
	},
	[10063] = {
		target_id = "0",
		name = "Eagle Union Emblem of Liberty",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who embodies the ideals of the Eagle Union as a protector of liberty and justice.",
		next = 10064,
		icon = "1013",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_101",
		condition = "Coming Soon",
		rank = 3,
		id = 10063,
		explain1 = "Awarded to those who bless the seas",
		explain2 = "with liberty and justice."
	},
	[10064] = {
		target_id = "0",
		name = "Eagle Union Emblem of Liberty",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who embodies the ideals of the Eagle Union as a protector of liberty and justice.",
		next = 10065,
		icon = "1014",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_101",
		condition = "Coming Soon",
		rank = 4,
		id = 10064,
		explain1 = "Awarded to those who bless the seas",
		explain2 = "with liberty and justice."
	},
	[10065] = {
		target_id = "0",
		name = "Eagle Union Emblem of Liberty",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who embodies the ideals of the Eagle Union as a protector of liberty and justice.",
		next = 0,
		icon = "1015",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_101",
		condition = "Coming Soon",
		rank = 5,
		id = 10065,
		explain1 = "Awarded to those who bless the seas",
		explain2 = "with liberty and justice."
	},
	[10071] = {
		name = "Royal Navy Cross of Valour",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the brave and indomitable commander who embodies the resplendence and glory of the Royal Navy.",
		next = 10072,
		icon = "1021",
		page = 1,
		target_type = 160,
		start = 0,
		hide = 0,
		label = "l_102",
		condition = "Using Royal Navy ships: Reach Level 120 on at least 12 different ships, reach a total of at least 2,000 Affinity, and earn at least 2M EXP.",
		rank = 1,
		id = 10071,
		explain1 = "Awarded to those who embody Her Majesty's glory",
		explain2 = "across a sea where the sun never sets.",
		target_id = {
			100711,
			100721,
			100731
		}
	},
	[10072] = {
		name = "Royal Navy Cross of Valour",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the brave and indomitable commander who embodies the resplendence and glory of the Royal Navy.",
		next = 10073,
		icon = "1022",
		page = 1,
		target_type = 160,
		start = 1,
		hide = 0,
		label = "l_102",
		condition = "Using Royal Navy ships: Reach Level 120 on at least 24 different ships, reach a total of at least 4,000 Affinity, and earn at least 2M EXP.",
		rank = 2,
		id = 10072,
		explain1 = "Awarded to those who embody Her Majesty's glory",
		explain2 = "across a sea where the sun never sets.",
		target_id = {
			100712,
			100722,
			100732
		}
	},
	[10073] = {
		target_id = "0",
		name = "Royal Navy Cross of Valour",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the brave and indomitable commander who embodies the resplendence and glory of the Royal Navy.",
		next = 10074,
		icon = "1023",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_102",
		condition = "Coming Soon",
		rank = 3,
		id = 10073,
		explain1 = "Awarded to those who embody Her Majesty's glory",
		explain2 = "across a sea where the sun never sets."
	},
	[10074] = {
		target_id = "0",
		name = "Royal Navy Cross of Valour",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the brave and indomitable commander who embodies the resplendence and glory of the Royal Navy.",
		next = 10075,
		icon = "1024",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_102",
		condition = "Coming Soon",
		rank = 4,
		id = 10074,
		explain1 = "Awarded to those who embody Her Majesty's glory",
		explain2 = "across a sea where the sun never sets."
	},
	[10075] = {
		target_id = "0",
		name = "Royal Navy Cross of Valour",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the brave and indomitable commander who embodies the resplendence and glory of the Royal Navy.",
		next = 0,
		icon = "1025",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_102",
		condition = "Coming Soon",
		rank = 5,
		id = 10075,
		explain1 = "Awarded to those who embody Her Majesty's glory",
		explain2 = "across a sea where the sun never sets."
	},
	[10081] = {
		name = "Sakura Empire Order of Merit",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who loves the people of the Sakura Empire and treasures the prosperity of our ancient lands.",
		next = 10082,
		icon = "1031",
		page = 1,
		target_type = 160,
		start = 0,
		hide = 0,
		label = "l_103",
		condition = "Using Sakura Empire ships: Reach Level 120 on at least 12 different ships, reach a total of at least 2,000 Affinity, and earn at least 2M EXP.",
		rank = 1,
		id = 10081,
		explain1 = "Awarded to those who are touched by the guardian deities",
		explain2 = "and protect the sanctity of the Sakura Empire's seas.",
		target_id = {
			100811,
			100821,
			100831
		}
	},
	[10082] = {
		name = "Sakura Empire Order of Merit",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who loves the people of the Sakura Empire and treasures the prosperity of our ancient lands.",
		next = 10083,
		icon = "1032",
		page = 1,
		target_type = 160,
		start = 1,
		hide = 0,
		label = "l_103",
		condition = "Using Sakura Empire ships: Reach Level 120 on at least 24 different ships, reach a total of at least 4,000 Affinity, and earn at least 2M EXP.",
		rank = 2,
		id = 10082,
		explain1 = "Awarded to those who are touched by the guardian deities",
		explain2 = "and protect the sanctity of the Sakura Empire's seas.",
		target_id = {
			100812,
			100822,
			100832
		}
	},
	[10083] = {
		target_id = "0",
		name = "Sakura Empire Order of Merit",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who loves the people of the Sakura Empire and treasures the prosperity of our ancient lands.",
		next = 10084,
		icon = "1033",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_103",
		condition = "Coming Soon",
		rank = 3,
		id = 10083,
		explain1 = "Awarded to those who are touched by the guardian deities",
		explain2 = "and protect the sanctity of the Sakura Empire's seas."
	},
	[10084] = {
		target_id = "0",
		name = "Sakura Empire Order of Merit",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who loves the people of the Sakura Empire and treasures the prosperity of our ancient lands.",
		next = 10085,
		icon = "1034",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_103",
		condition = "Coming Soon",
		rank = 4,
		id = 10084,
		explain1 = "Awarded to those who are touched by the guardian deities",
		explain2 = "and protect the sanctity of the Sakura Empire's seas."
	},
	[10085] = {
		target_id = "0",
		name = "Sakura Empire Order of Merit",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who loves the people of the Sakura Empire and treasures the prosperity of our ancient lands.",
		next = 0,
		icon = "1035",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_103",
		condition = "Coming Soon",
		rank = 5,
		id = 10085,
		explain1 = "Awarded to those who are touched by the guardian deities",
		explain2 = "and protect the sanctity of the Sakura Empire's seas."
	},
	[10091] = {
		name = "Iron Blood Adamant Medal",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who has attained the pinnacle of valor in exhibiting the majesty of the Iron Blood.",
		next = 10092,
		icon = "1041",
		page = 1,
		target_type = 160,
		start = 0,
		hide = 0,
		label = "l_104",
		condition = "Using Iron Blood ships: Reach Level 120 on at least 12 different ships, reach a total of at least 2,000 Affinity, and earn at least 2M EXP.",
		rank = 1,
		id = 10091,
		explain1 = "for the sake of their comrades in the Iron Blood.",
		explain2 = "Awarded to those who have become a pillar of strength",
		target_id = {
			100911,
			100921,
			100931
		}
	},
	[10092] = {
		name = "Iron Blood Adamant Medal",
		target_num = 3,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who has attained the pinnacle of valor in exhibiting the majesty of the Iron Blood.",
		next = 10093,
		icon = "1042",
		page = 1,
		target_type = 160,
		start = 1,
		hide = 0,
		label = "l_104",
		condition = "Using Iron Blood ships: Reach Level 120 on at least 24 different ships, reach a total of at least 4,000 Affinity, and earn at least 2M EXP.",
		rank = 2,
		id = 10092,
		explain1 = "for the sake of their comrades in the Iron Blood.",
		explain2 = "Awarded to those who have become a pillar of strength",
		target_id = {
			100912,
			100922,
			100932
		}
	},
	[10093] = {
		target_id = "0",
		name = "Iron Blood Adamant Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who has attained the pinnacle of valor in exhibiting the majesty of the Iron Blood.",
		next = 10094,
		icon = "1043",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_104",
		condition = "Coming Soon",
		rank = 3,
		id = 10093,
		explain1 = "for the sake of their comrades in the Iron Blood.",
		explain2 = "Awarded to those who have become a pillar of strength"
	},
	[10094] = {
		target_id = "0",
		name = "Iron Blood Adamant Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who has attained the pinnacle of valor in exhibiting the majesty of the Iron Blood.",
		next = 10095,
		icon = "1044",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_104",
		condition = "Coming Soon",
		rank = 4,
		id = 10094,
		explain1 = "for the sake of their comrades in the Iron Blood.",
		explain2 = "Awarded to those who have become a pillar of strength"
	},
	[10095] = {
		target_id = "0",
		name = "Iron Blood Adamant Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander who has attained the pinnacle of valor in exhibiting the majesty of the Iron Blood.",
		next = 0,
		icon = "1045",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_104",
		condition = "Coming Soon",
		rank = 5,
		id = 10095,
		explain1 = "for the sake of their comrades in the Iron Blood.",
		explain2 = "Awarded to those who have become a pillar of strength"
	},
	[10101] = {
		target_id = "0",
		name = "Naval F.L.E.X. Medal",
		target_num = 100,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander whose dedication and wisdom earned the loyalty of many, we award the Fleet Leader Excellence medal.",
		next = 10102,
		icon = "2011",
		page = 1,
		target_type = 1044,
		start = 0,
		hide = 0,
		label = "l_206",
		condition = "Have at least 100 ships unlocked in the Collection Archives.",
		rank = 1,
		id = 10101,
		explain1 = "Awarded to those whose leadership was pivotal",
		explain2 = "to the growth and expansion of the fleet."
	},
	[10102] = {
		target_id = "0",
		name = "Naval F.L.E.X. Medal",
		target_num = 200,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander whose dedication and wisdom earned the loyalty of many, we award the Fleet Leader Excellence medal.",
		next = 10103,
		icon = "2012",
		page = 1,
		target_type = 1044,
		start = 1,
		hide = 0,
		label = "l_206",
		condition = "Have at least 200 ships unlocked in the Collection Archives.",
		rank = 2,
		id = 10102,
		explain1 = "Awarded to those whose leadership was pivotal",
		explain2 = "to the growth and expansion of the fleet."
	},
	[10103] = {
		target_id = "0",
		name = "Naval F.L.E.X. Medal",
		target_num = 300,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander whose dedication and wisdom earned the loyalty of many, we award the Fleet Leader Excellence medal.",
		next = 10104,
		icon = "2013",
		page = 1,
		target_type = 1044,
		start = 1,
		hide = 0,
		label = "l_206",
		condition = "Have at least 300 ships unlocked in the Collection Archives.",
		rank = 3,
		id = 10103,
		explain1 = "Awarded to those whose leadership was pivotal",
		explain2 = "to the growth and expansion of the fleet."
	},
	[10104] = {
		target_id = "0",
		name = "Naval F.L.E.X. Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander whose dedication and wisdom earned the loyalty of many, we award the Fleet Leader Excellence medal.",
		next = 10105,
		icon = "2014",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_206",
		condition = "Coming Soon",
		rank = 4,
		id = 10104,
		explain1 = "Awarded to those whose leadership was pivotal",
		explain2 = "to the growth and expansion of the fleet."
	},
	[10105] = {
		target_id = "0",
		name = "Naval F.L.E.X. Medal",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "To the commander whose dedication and wisdom earned the loyalty of many, we award the Fleet Leader Excellence medal.",
		next = 0,
		icon = "2015",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "l_206",
		condition = "Coming Soon",
		rank = 5,
		id = 10105,
		explain1 = "Awarded to those whose leadership was pivotal",
		explain2 = "to the growth and expansion of the fleet."
	},
	[100611] = {
		name = "白鹰阵营子勋章1",
		target_num = 12,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 12 different Eagle Union ships",
		rank = 1,
		id = 100611,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				1,
				120
			}
		}
	},
	[100612] = {
		name = "白鹰阵营子勋章1",
		target_num = 24,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 24 different Eagle Union ships",
		rank = 2,
		id = 100612,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				1,
				120
			}
		}
	},
	[100613] = {
		target_id = "0",
		name = "白鹰阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100613,
		explain1 = "",
		explain2 = ""
	},
	[100614] = {
		target_id = "0",
		name = "白鹰阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100614,
		explain1 = "",
		explain2 = ""
	},
	[100615] = {
		target_id = "0",
		name = "白鹰阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100615,
		explain1 = "",
		explain2 = ""
	},
	[100621] = {
		target_id = "1",
		name = "白鹰阵营子勋章2",
		target_num = 200000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 2000 total Affinity with Eagle Union ships",
		rank = 1,
		id = 100621,
		explain1 = "",
		explain2 = ""
	},
	[100622] = {
		target_id = "1",
		name = "白鹰阵营子勋章2",
		target_num = 400000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 4000 total Affinity with Eagle Union ships",
		rank = 2,
		id = 100622,
		explain1 = "",
		explain2 = ""
	},
	[100623] = {
		target_id = "0",
		name = "白鹰阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100623,
		explain1 = "",
		explain2 = ""
	},
	[100624] = {
		target_id = "0",
		name = "白鹰阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100624,
		explain1 = "",
		explain2 = ""
	},
	[100625] = {
		target_id = "0",
		name = "白鹰阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100625,
		explain1 = "",
		explain2 = ""
	},
	[100631] = {
		name = "白鹰阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Eagle Union ships",
		rank = 1,
		id = 100631,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				1,
				0
			}
		}
	},
	[100632] = {
		name = "白鹰阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Eagle Union ships",
		rank = 2,
		id = 100632,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				1,
				0
			}
		}
	},
	[100633] = {
		target_id = "0",
		name = "白鹰阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100633,
		explain1 = "",
		explain2 = ""
	},
	[100634] = {
		target_id = "0",
		name = "白鹰阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100634,
		explain1 = "",
		explain2 = ""
	},
	[100635] = {
		target_id = "0",
		name = "白鹰阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100635,
		explain1 = "",
		explain2 = ""
	},
	[100711] = {
		name = "皇家阵营子勋章1",
		target_num = 12,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 12 different Royal Navy ships",
		rank = 1,
		id = 100711,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				2,
				120
			}
		}
	},
	[100712] = {
		name = "皇家阵营子勋章1",
		target_num = 24,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 24 different Royal Navy ships",
		rank = 2,
		id = 100712,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				2,
				120
			}
		}
	},
	[100713] = {
		target_id = "0",
		name = "皇家阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100713,
		explain1 = "",
		explain2 = ""
	},
	[100714] = {
		target_id = "0",
		name = "皇家阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100714,
		explain1 = "",
		explain2 = ""
	},
	[100715] = {
		target_id = "0",
		name = "皇家阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100715,
		explain1 = "",
		explain2 = ""
	},
	[100721] = {
		target_id = "2",
		name = "皇家阵营子勋章2",
		target_num = 200000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 2000 total Affinity with Royal Navy ships",
		rank = 1,
		id = 100721,
		explain1 = "",
		explain2 = ""
	},
	[100722] = {
		target_id = "2",
		name = "皇家阵营子勋章2",
		target_num = 400000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 4000 total Affinity with Royal Navy ships",
		rank = 2,
		id = 100722,
		explain1 = "",
		explain2 = ""
	},
	[100723] = {
		target_id = "0",
		name = "皇家阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100723,
		explain1 = "",
		explain2 = ""
	},
	[100724] = {
		target_id = "0",
		name = "皇家阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100724,
		explain1 = "",
		explain2 = ""
	},
	[100725] = {
		target_id = "0",
		name = "皇家阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100725,
		explain1 = "",
		explain2 = ""
	},
	[100731] = {
		name = "皇家阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Royal Navy ships",
		rank = 1,
		id = 100731,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				2,
				0
			}
		}
	},
	[100732] = {
		name = "皇家阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Royal Navy ships",
		rank = 2,
		id = 100732,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				2,
				0
			}
		}
	},
	[100733] = {
		target_id = "0",
		name = "皇家阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100733,
		explain1 = "",
		explain2 = ""
	},
	[100734] = {
		target_id = "0",
		name = "皇家阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100734,
		explain1 = "",
		explain2 = ""
	},
	[100735] = {
		target_id = "0",
		name = "皇家阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100735,
		explain1 = "",
		explain2 = ""
	},
	[100811] = {
		name = "重樱阵营子勋章1",
		target_num = 12,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 12 different Sakura Empire ships",
		rank = 1,
		id = 100811,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				3,
				120
			}
		}
	},
	[100812] = {
		name = "重樱阵营子勋章1",
		target_num = 24,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 24 different Sakura Empire ships",
		rank = 2,
		id = 100812,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				3,
				120
			}
		}
	},
	[100813] = {
		target_id = "0",
		name = "重樱阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100813,
		explain1 = "",
		explain2 = ""
	},
	[100814] = {
		target_id = "0",
		name = "重樱阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100814,
		explain1 = "",
		explain2 = ""
	},
	[100815] = {
		target_id = "0",
		name = "重樱阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100815,
		explain1 = "",
		explain2 = ""
	},
	[100821] = {
		target_id = "3",
		name = "重樱阵营子勋章2",
		target_num = 200000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 2000 total Affinity with Sakura Empire ships",
		rank = 1,
		id = 100821,
		explain1 = "",
		explain2 = ""
	},
	[100822] = {
		target_id = "3",
		name = "重樱阵营子勋章2",
		target_num = 400000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 4000 total Affinity with Sakura Empire ships",
		rank = 2,
		id = 100822,
		explain1 = "",
		explain2 = ""
	},
	[100823] = {
		target_id = "0",
		name = "重樱阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100823,
		explain1 = "",
		explain2 = ""
	},
	[100824] = {
		target_id = "0",
		name = "重樱阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100824,
		explain1 = "",
		explain2 = ""
	},
	[100825] = {
		target_id = "0",
		name = "重樱阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100825,
		explain1 = "",
		explain2 = ""
	},
	[100831] = {
		name = "重樱阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Sakura Empire ships",
		rank = 1,
		id = 100831,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				3,
				0
			}
		}
	},
	[100832] = {
		name = "重樱阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Sakura Empire ships",
		rank = 2,
		id = 100832,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				3,
				0
			}
		}
	},
	[100833] = {
		target_id = "0",
		name = "重樱阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100833,
		explain1 = "",
		explain2 = ""
	},
	[100834] = {
		target_id = "0",
		name = "重樱阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100834,
		explain1 = "",
		explain2 = ""
	},
	[100835] = {
		target_id = "0",
		name = "重樱阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100835,
		explain1 = "",
		explain2 = ""
	},
	[100911] = {
		name = "铁血阵营子勋章1",
		target_num = 12,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 12 different Iron Blood ships",
		rank = 1,
		id = 100911,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				4,
				120
			}
		}
	},
	[100912] = {
		name = "铁血阵营子勋章1",
		target_num = 24,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1042,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach Level 120 on at least 24 different Iron Blood ships",
		rank = 2,
		id = 100912,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				4,
				120
			}
		}
	},
	[100913] = {
		target_id = "0",
		name = "铁血阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100913,
		explain1 = "",
		explain2 = ""
	},
	[100914] = {
		target_id = "0",
		name = "铁血阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100914,
		explain1 = "",
		explain2 = ""
	},
	[100915] = {
		target_id = "0",
		name = "铁血阵营子勋章1",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100915,
		explain1 = "",
		explain2 = ""
	},
	[100921] = {
		target_id = "4",
		name = "铁血阵营子勋章2",
		target_num = 200000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 2000 total Affinity with Iron Blood ships",
		rank = 1,
		id = 100921,
		explain1 = "",
		explain2 = ""
	},
	[100922] = {
		target_id = "4",
		name = "铁血阵营子勋章2",
		target_num = 400000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1043,
		start = 1,
		hide = 1,
		label = "",
		condition = "Reach 4000 total Affinity with Iron Blood ships",
		rank = 2,
		id = 100922,
		explain1 = "",
		explain2 = ""
	},
	[100923] = {
		target_id = "0",
		name = "铁血阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100923,
		explain1 = "",
		explain2 = ""
	},
	[100924] = {
		target_id = "0",
		name = "铁血阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100924,
		explain1 = "",
		explain2 = ""
	},
	[100925] = {
		target_id = "0",
		name = "铁血阵营子勋章2",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100925,
		explain1 = "",
		explain2 = ""
	},
	[100931] = {
		name = "铁血阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Iron Blood ships",
		rank = 1,
		id = 100931,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				4,
				0
			}
		}
	},
	[100932] = {
		name = "铁血阵营子勋章3",
		target_num = 2000000,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 1041,
		start = 1,
		hide = 1,
		label = "",
		condition = "Earn at least 2 million EXP with Iron Blood ships",
		rank = 2,
		id = 100932,
		explain1 = "",
		explain2 = "",
		target_id = {
			{
				4,
				0
			}
		}
	},
	[100933] = {
		target_id = "0",
		name = "铁血阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 3,
		id = 100933,
		explain1 = "",
		explain2 = ""
	},
	[100934] = {
		target_id = "0",
		name = "铁血阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 4,
		id = 100934,
		explain1 = "",
		explain2 = ""
	},
	[100935] = {
		target_id = "0",
		name = "铁血阵营子勋章3",
		target_num = 1,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "",
		next = 0,
		icon = "",
		page = 1,
		target_type = 9999,
		start = 1,
		hide = 3,
		label = "",
		condition = "Coming Soon",
		rank = 5,
		id = 100935,
		explain1 = "",
		explain2 = ""
	},
	[200001] = {
		target_id = "5711",
		name = "Stellar Resistance Medal",
		target_num = 8,
		type = 0,
		is_out_of_print = 1,
		count_inherit = 0,
		desc = "A commemorative medal issued by the Iron Blood Resistance celebrating your triumph over the Star Beast.\n—Our world shall not perish. Not today, not ever.",
		next = 0,
		icon = "9001",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9001",
		condition = "Collect 8 commemorative stickers from \"Substellar Crepuscule\".",
		rank = 1,
		id = 200001,
		explain1 = "Substellar Crepuscule",
		explain2 = "Event"
	},
	[200011] = {
		target_id = "5769",
		name = "Spring Fashion Festa Medal",
		target_num = 8,
		type = 0,
		is_out_of_print = 1,
		count_inherit = 0,
		desc = "Despite twists and turns, long last are wishes granted. Amidst flowing light, colorfully is the night painted.",
		next = 0,
		icon = "9011",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9011",
		condition = "Collect 8 commemorative stickers from Spring Fashion Festa.",
		rank = 1,
		id = 200011,
		explain1 = "Spring Fashion Festa",
		explain2 = "Event"
	},
	[200021] = {
		target_id = "5812",
		name = "Wings of Holy Light Medal",
		target_num = 8,
		type = 0,
		is_out_of_print = 1,
		count_inherit = 0,
		desc = "A medal awarded by the Sardegnia League. It commemorates their victory against the immensely powerful MECHArbiter.\n—What awaits us outside the cage is hope and glory.",
		next = 0,
		icon = "9021",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9021",
		condition = "Collect 8 commemorative stickers from Paradiso of Shackled Light",
		rank = 1,
		id = 200021,
		explain1 = "「Paradiso of Shackled Light」",
		explain2 = "Event"
	},
	[200031] = {
		target_id = "5875",
		name = "Valley Hospital Investigation Medal",
		target_num = 8,
		type = 0,
		is_out_of_print = 1,
		count_inherit = 0,
		desc = "Congratulations! You uncovered Valley Hospital's secrets and reached the best ending. Did you have fun?",
		next = 0,
		icon = "9031",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9031",
		condition = "Collect 8 commemorative stickers from Letters from Valley Hospital",
		rank = 1,
		id = 200031,
		explain1 = "Letters from Valley Hospital",
		explain2 = "Event"
	},
	[200041] = {
		target_id = "5913",
		name = "Tulipa Commemorative Medal",
		target_num = 8,
		type = 0,
		is_out_of_print = 1,
		count_inherit = 0,
		desc = "A medal from the Kingdom of Tulipa. It commemorates the defense of their country. \n—A new age of unity has begun.",
		next = 0,
		icon = "9041",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9041",
		condition = "Collect 8 stickers in Toward Tulipa's Seas.",
		rank = 1,
		id = 200041,
		explain1 = "Toward Tulipa's Seas",
		explain2 = "Event"
	},
	[200051] = {
		target_id = "5970",
		name = "A Rose on the High Tower Medal",
		target_num = 8,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "The high tower crumbles, yet the rose rises from its ruins.\nThough this story has its ups and downs, the ending is a satisfactory one. Congratulations are in order.",
		next = 0,
		icon = "9051",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9051",
		condition = "Collect 8 stickers in A Rose on the High Tower.",
		rank = 1,
		id = 200051,
		explain1 = "A Rose on the High Tower.",
		explain2 = "Event"
	},
	[200061] = {
		target_id = "5971",
		name = "The Villa Reconstruction Medal",
		target_num = 7,
		type = 0,
		is_out_of_print = 0,
		count_inherit = 0,
		desc = "Sandy beaches, warm sunshine, breezy AC, and refreshing drinks – enjoy this villa vacation on a resort island to its fullest!",
		next = 0,
		icon = "9061",
		page = 2,
		target_type = 131,
		start = 0,
		hide = 0,
		label = "l_9061",
		condition = "Collect 7 stickers in Midsummer Returns: The Villa Reconstruction.",
		rank = 1,
		id = 200061,
		explain1 = "The Villa Reconstruction.",
		explain2 = "Event"
	},
	all = {
		10011,
		10012,
		10013,
		10014,
		10015,
		10021,
		10022,
		10023,
		10024,
		10025,
		10031,
		10032,
		10033,
		10034,
		10035,
		10041,
		10042,
		10043,
		10044,
		10045,
		10051,
		10052,
		10053,
		10054,
		10055,
		10061,
		10062,
		10063,
		10064,
		10065,
		10071,
		10072,
		10073,
		10074,
		10075,
		10081,
		10082,
		10083,
		10084,
		10085,
		10091,
		10092,
		10093,
		10094,
		10095,
		10101,
		10102,
		10103,
		10104,
		10105,
		100611,
		100612,
		100613,
		100614,
		100615,
		100621,
		100622,
		100623,
		100624,
		100625,
		100631,
		100632,
		100633,
		100634,
		100635,
		100711,
		100712,
		100713,
		100714,
		100715,
		100721,
		100722,
		100723,
		100724,
		100725,
		100731,
		100732,
		100733,
		100734,
		100735,
		100811,
		100812,
		100813,
		100814,
		100815,
		100821,
		100822,
		100823,
		100824,
		100825,
		100831,
		100832,
		100833,
		100834,
		100835,
		100911,
		100912,
		100913,
		100914,
		100915,
		100921,
		100922,
		100923,
		100924,
		100925,
		100931,
		100932,
		100933,
		100934,
		100935,
		200001,
		200011,
		200021,
		200031,
		200041,
		200051,
		200061
	}
}
