_G.pg.item_data_statistics[59008] = {
	display = "A new currency issued by HQ for contributions made to one's Guild. It can be used even after leaving or joining a new Guild. ",
	name = "Fleet Currency",
	rarity = 2,
	type = 98,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59008,
	is_world = 0,
	icon = "Props/guildIcon",
	display_icon = {},
	price = {},
	index = {}
}
