_G.pg.item_data_statistics[59185] = {
	display = "\"Universe in Unison\" reward exchange currency. Expires after the event ends. ",
	name = "Universe Badge",
	rarity = 2,
	type = 98,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59185,
	is_world = 0,
	icon = "Props/music2_pt",
	display_icon = {},
	price = {},
	index = {}
}
