_G.pg.item_data_statistics[59201] = {
	display = "The keys to finding the Sirens' facility, which surely houses many secrets and treasures. Event exchange currency. Will be removed from your inventory after the event period ends.",
	name = "Arcana Cube",
	rarity = 2,
	type = 98,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59201,
	is_world = 0,
	icon = "Props/beilian2_pt",
	display_icon = {},
	price = {},
	index = {}
}
