_G.pg.item_data_statistics[59721] = {
	display = "A letter from San Diego. It reads: \"Heeeey~! Happy 1-year anniversary~!\"",
	name = "San Diego's Letter",
	rarity = 9,
	type = 1,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59721,
	is_world = 0,
	icon = "Props/yaoqinghan",
	display_icon = {},
	price = {},
	index = {}
}
