_G.pg.item_data_statistics[59787] = {
	display = "Collect 7 of them to receive limited character \"Sheffield (Muse)\".",
	name = "New Year's Blessings",
	rarity = 2,
	type = 0,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59787,
	is_world = 0,
	icon = "props/music_stage",
	display_icon = {},
	price = {},
	index = {}
}
