_G.pg.item_data_statistics[59973] = {
	display = "Paint D, used in the Coloring Book event. Will be removed after the event ends",
	name = "Pigment D",
	rarity = 2,
	type = 0,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 4,
	link_id = 30473,
	id = 59973,
	is_world = 0,
	icon = "props/z23draw_d",
	display_icon = {},
	price = {},
	index = {}
}
