_G.pg.item_data_statistics[9] = {
	display = "T3 76mm Artillery Design",
	name = "T3 76mm Artillery Design",
	rarity = 2,
	type = 9,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 9,
	is_world = 0,
	icon = "Equips/11000",
	display_icon = {},
	price = {},
	index = {}
}
