_G.pg.item_data_statistics[1011] = {
	display = "An important document that details the progress of the operation. Crucial reference material that allows the Naval HQ to assess the situation and approve future actions.",
	name = "Operation Report",
	rarity = 3,
	type = 1,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 1011,
	is_world = 0,
	icon = "Props/zuozhanbaogao",
	display_icon = {},
	price = {},
	index = {}
}
