_G.pg.item_data_statistics[41912] = {
	display = "A Valentine Gift from Glasgow",
	name = "Valentine Gift ",
	rarity = 8,
	type = 1,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 41912,
	is_world = 0,
	icon = "SquareIcon/gelasige",
	display_icon = {},
	price = {},
	index = {}
}
