_G.pg.item_data_statistics[54006] = {
	display = "Chance to receive a random T3 skill book",
	name = "T3 Mystery Skill Book",
	rarity = 4,
	type = 98,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 54006,
	is_world = 0,
	icon = "Props/54003",
	display_icon = {},
	price = {},
	index = {}
}
