_G.pg.item_data_statistics[13013] = {
	display = "Prototype Twin 406mm Main Gun (SK C/34) T0 Design",
	name = "Prototype Twin 406mm Main Gun (SK C/34) T0 Design",
	rarity = 4,
	type = 9,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 13013,
	is_world = 0,
	icon = "Equips/44200",
	display_icon = {},
	price = {},
	index = {}
}
