_G.pg.item_data_statistics[59948] = {
	display = "「あけましておめでとう。今年もともに陛下に忠義を尽くすわよ」――ウォースパイトからのお礼",
	name = "ウォースパイトからのお礼（正月） ",
	rarity = 9,
	type = 1,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 59948,
	is_world = 0,
	icon = "Props/nianhezhuang",
	display_icon = {},
	price = {},
	index = {}
}
