_G.pg.item_data_statistics[41502] = {
	display = "ローン からのバレンタインプレゼント",
	name = "バレンタインプレゼント",
	rarity = 8,
	type = 1,
	drop_oil_max = 0,
	shiptrans_id = 0,
	shop_id = -1,
	replace_item = 0,
	drop_gold_max = 0,
	virtual_type = 0,
	link_id = 0,
	id = 41502,
	is_world = 0,
	icon = "SquareIcon/luoen",
	display_icon = {},
	price = {},
	index = {}
}
